### PR TITLE
Rebuild taxmap

### PR DESCRIPTION
**Pull request by zachary-foster**
These are the changes discussed in issue #16.

### CODE REVIEW

**Comment by zachary-foster** [comment]
Hmm. Do you know what the deal is with all the Travis CI errors. R CMD Check passed with no warnings or notes on my computer. Should I be committing the files in `man`? I have not been since they are automatically produced and I did not want to inflate the size of the repository unnecessarily.

**Comment by sckott** [comment]
thanks, I'll have a look

**Comment by sckott** [comment]
@zachary-foster you can see on travis check is running with `--as-cran` https://travis-ci.org/ropenscilabs/taxa/jobs/206828627#L2355 

which checks for mismatches in docs in .Rd and .R files and other things - i'm guessing you weren’t using `--as-cran` locally?

please do generate new `.Rd` files however you do that - `devtools::document()`, `roxygen2::roxygenise()`, or other - adds more file changes, but necessary to do so

**Comment by zachary-foster** [comment]
Oh ok, I have updated the man pages. I use `devtools::document(roclets=c('rd', 'collate', 'namespace'))` and  `devtools::check(args = c('--as-cran'))`

**Comment by sckott** [comment]
passing now, nice

**Comment by sckott** [comment]
Went through the changes and ran examples, etc. 

I think there's a few things i'd like to change (e.g., add some R6 docs, tidy to 80 line width) and could be changed (https://github.com/ropenscilabs/taxa/issues/16#issuecomment-283529307) - but I think i'd like to merge this, then we can add more egs and tests and  in the process I'll better understand the new stuff - and other things may come up - but so far I really like it. 

Okay if i merge?

**Comment by zachary-foster** [comment]
@sckott Yea, go ahead and merge it. Im glad you like it so far! Sounds like a plan.

**Pull request merged**
