### PR TITLE
Importing new version of functions from metacoder

### PR DESCRIPTION
**Pull request by zachary-foster**
Hi @sckott. Sorry I have not talked to you about this repo in a while. We are about to submit `metacoder` to CRAN and submit its publication. I have talked to my advisor, Niklaus Grunwald, and he is OK with moving the taxonomy class (called `taxmap` in metacoder) and its associated functions into `taxa` and continuing development there. 

The functions have changed quite a bit since you last saw them. The manipulation functions are now modelled after dplyr. They are basically an adaptation of dplyr to a pair of data.frames in the same object: tabular data (called 'observations') mapped to hierarchical data (called `taxa`). There is also support for "virtual columns" in both tables that can be used like normal columns in most situations. Everything is still S3, but I am ok with changing this.

There are tests and full help pages with examples that should allow you to make sense of things. To get an overall idea of how this set of functions is intended to be used see how metacoder uses them here:

https://grunwaldlab.github.io/metacoder_documentation/vignettes--03--manipulating_taxonomic_data.html
https://grunwaldlab.github.io/metacoder_documentation/vignettes--04--hierarchical_subsampling.html 

The website just went up and a few pages dont work yet, but those should.

Let me know if you have problems/questions.

### CODE REVIEW

**Comment by zachary-foster** [comment]
hmm, the checks passed on my computer. I will look into this soon

**Comment by sckott** [comment]
thanks, having a look

**Comment by zachary-foster** [comment]
Nice.

I replaced the example dataset so the function examples in the man pages should work now.

**Comment by sckott** [comment]
@zachary-foster looks good to me. merging. 

opening up a new issue to talk about where to go from here

**Pull request merged**
